# Generated by Django 2.2 on 2019-06-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phdfellows', '0002_writtentestscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantScoreByFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willing_to_guide', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('assesment_score', models.IntegerField(null=True)),
                ('remarks', models.TextField()),
                ('application_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phdfellows.Application')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
