# Generated by Django 2.2 on 2019-06-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0017_auto_20190620_1054'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
