# Generated by Django 2.2 on 2019-06-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_delete_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
