# Generated by Django 2.2 on 2019-06-25 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'Select'), ('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('EWS', 'EWS'), ('General', 'General')], default='Select', max_length=10)),
                ('having_disability', models.BooleanField(default=False, verbose_name='Disabled')),
                ('research_area', models.CharField(choices=[('', 'Select'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Airtifial Intelligence', 'Airtifial Intelligence'), ('Software Development', 'Software Development'), ('Cryptography', 'Cryptography')], default='Select', max_length=50)),
                ('applying_for', models.CharField(choices=[('', 'Select'), ('PhD', 'PhD'), ('MS', 'MS')], default='Select', max_length=5)),
                ('enrollment_type', models.CharField(choices=[('', 'Select'), ('Full time', 'Full time'), ('Part time', 'Part time')], default='Select', max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=10, null=True, verbose_name='Date of Birth')),
                ('married', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Select', max_length=20)),
                ('phone_no', models.CharField(max_length=13, verbose_name='Phone Number(With Country Code)')),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')])),
                ('score_in_ug', models.FloatField(default=None, null=True, verbose_name='Score in UG')),
                ('scale_of_score_ug', models.CharField(choices=[('', 'Select'), ('0-5 CGPA', '0-5 CGPA'), ('0-10 CGPA', '0-10 CGPA'), ('0-100%', '0-100%')], default='Select', max_length=20, verbose_name='Scale of Score')),
                ('ug_discipline', models.CharField(choices=[('', 'Select'), ('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], default='Select', max_length=20, verbose_name='UG Discipline')),
                ('ug_college_or_university', models.CharField(max_length=200, verbose_name='UG College/University')),
                ('pg_passed_or_expected_to_pass_in_year', models.IntegerField(default=None, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')], verbose_name='PG Passed Year or Expected to Pass in Year')),
                ('score_in_pg', models.FloatField(default=None, null=True, verbose_name='Score in PG')),
                ('scale_of_score_pg', models.CharField(choices=[('', 'Select'), ('0-5 CGPA', '0-5 CGPA'), ('0-10 CGPA', '0-10 CGPA'), ('0-100%', '0-100%')], default='Select', max_length=20, verbose_name='Scale of Score')),
                ('pg_discipline', models.CharField(choices=[('', 'Select'), ('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], default='Select', max_length=50, verbose_name='PG Discipline')),
                ('pg_college_or_university', models.CharField(max_length=200, verbose_name='PG College/University')),
                ('qualifying_examination', models.CharField(choices=[('', 'Select'), ('GATE', 'GATE'), ('NET', 'NET')], default='Select', max_length=20)),
                ('branch_code_for_qualifying_exam', models.CharField(choices=[('', 'Select'), ('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], default='Select', max_length=10)),
                ('qualifying_exam_score_valid_upto', models.IntegerField(default=None, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
                ('all_india_rank_in_qualifying_exam', models.IntegerField(default=None, null=True, verbose_name='All India rank in Qualifying Exam')),
                ('score_in_qualifying_exam', models.FloatField(default=None, null=True)),
                ('work_experience_in_year', models.CharField(max_length=3, verbose_name='Work Experpience(in years)')),
                ('type_of_work', models.CharField(choices=[('', 'Select'), ('Teaching', 'Teaching'), ('IT Industry', 'IT Industry'), ('Research Organisation', 'Research Organisation'), ('Other', 'Other')], default='Select', max_length=50)),
                ('no_of_peer_reviewed_publications', models.IntegerField(default=0, null=True)),
                ('no_of_patents_granted', models.IntegerField(default=0, null=True)),
                ('guide_preference_1', models.CharField(max_length=200)),
                ('guide_preference_2', models.CharField(max_length=200)),
                ('guide_preference_3', models.CharField(max_length=200)),
                ('current_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Shortlisted for Test', 'Shortlisted for Test'), ('Shortlisted for Interview', 'Shortlisted for Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Draft', max_length=30)),
                ('submitted_at', models.DateField(auto_now=True)),
                ('application_no', models.IntegerField(default=None, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
