# Generated by Django 2.2 on 2019-06-10 09:29

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdFellows',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')])),
                ('category', models.CharField(choices=[('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('EWS', 'EWS'), ('General', 'General')], default='General', max_length=10)),
                ('having_disability', models.BooleanField(default=False)),
                ('research_area', models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Airtifial Intelligence', 'Airtifial Intelligence'), ('Software Development', 'Software Development'), ('Cryptography', 'Cryptography')], max_length=50)),
                ('enrollment_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name=datetime.date(2019, 6, 10))),
                ('martial_status', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')])),
                ('score_in_ug', models.FloatField()),
                ('scale_of_score_ug', models.CharField(choices=[('0-5 CGPA', '0-5 CGPA'), ('0-10 CGPA', '0-10 CGPA'), ('0-100%', '0-100%')], max_length=20, verbose_name='Scale of Score')),
                ('ug_discipline', models.CharField(choices=[('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], max_length=20)),
                ('pg_passed_or_expected_to_pass_in_year', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
                ('score_in_pg', models.FloatField()),
                ('scale_of_score_pg', models.CharField(choices=[('0-5 CGPA', '0-5 CGPA'), ('0-10 CGPA', '0-10 CGPA'), ('0-100%', '0-100%')], max_length=20, verbose_name='Scale of Score')),
                ('pg_discipline', models.CharField(choices=[('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], max_length=50)),
                ('ug_college_or_university', models.CharField(max_length=20, verbose_name='UG College/University')),
                ('qualifying_examination', models.CharField(choices=[('GATE', 'GATE'), ('NET', 'NET')], max_length=20)),
                ('branch_code_for_qualifying_exam', models.CharField(choices=[('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('ECE', 'ECE'), ('CE', 'CE')], max_length=10)),
                ('qualifying_exam_score_valid_upto', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
                ('all_india_rank_in_qualifying_exam', models.IntegerField()),
                ('score_in_qualifying_exam', models.IntegerField()),
                ('work_experience_in_year', models.IntegerField(verbose_name='Work Experpience(in years)')),
                ('type_of_work', models.CharField(choices=[('Teaching', 'Teaching'), ('IT Industry', 'IT Industry'), ('Research Organisation', 'Research Organisation'), ('Other', 'Other')], max_length=50)),
                ('no_of_peer_reviewed_publications', models.IntegerField()),
                ('no_of_patents_granted', models.IntegerField()),
                ('guide_preference_1', models.CharField(max_length=200)),
                ('guide_preference_2', models.CharField(max_length=200)),
                ('guide_preference_3', models.CharField(max_length=200)),
                ('phdfellow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phdfellows.PhdFellows')),
            ],
        ),
    ]
