# Generated by Django 2.2 on 2019-06-12 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')]),
        ),
    ]
