# Generated by Django 2.2 on 2019-06-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phdfellow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
