# Generated by Django 2.2 on 2019-06-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenTestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_test_score', models.IntegerField(null=True)),
                ('programming_test_score', models.IntegerField(null=True)),
                ('application_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phdfellows.Application')),
            ],
        ),
    ]
