# Generated by Django 2.2 on 2019-06-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0002_writtentestscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='was_selected_for_interview',
            field=models.BooleanField(default=False),
        ),
    ]
