# Generated by Django 2.2 on 2019-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0003_auto_20190612_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score_in_ug',
            field=models.FloatField(default=None, verbose_name='Score in UG'),
        ),
    ]
