# Generated by Django 2.2 on 2019-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0003_application_was_selected_for_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(default='Select', max_length=100),
        ),
    ]
