# Generated by Django 2.2 on 2019-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0004_auto_20190703_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_category_other',
            field=models.BooleanField(default=False),
        ),
    ]
