# Generated by Django 2.2 on 2019-06-12 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0005_auto_20190612_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='all_india_rank_in_qualifying_exam',
            field=models.IntegerField(default=None, null=True, verbose_name='All India rank in Qualifying Exam'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='no_of_patents_granted',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='no_of_peer_reviewed_publications',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='pg_passed_or_expected_to_pass_in_year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')], verbose_name='PG Passed Year or Expected to Pass in Year'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualifying_exam_score_valid_upto',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='score_in_pg',
            field=models.FloatField(default=None, null=True, verbose_name='Score in PG'),
        ),
        migrations.AlterField(
            model_name='application',
            name='score_in_qualifying_exam',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='score_in_ug',
            field=models.FloatField(default=None, null=True, verbose_name='Score in UG'),
        ),
    ]
