# Generated by Django 2.2 on 2019-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0005_application_is_category_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='branch_code_for_qualifying_exam',
            field=models.CharField(default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='pg_discipline',
            field=models.CharField(default='Select', max_length=100, verbose_name='PG Discipline'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ug_discipline',
            field=models.CharField(default='Select', max_length=100, verbose_name='UG Discipline'),
        ),
    ]
