# Generated by Django 2.2 on 2019-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0006_auto_20190612_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
