# Generated by Django 2.2 on 2019-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0009_auto_20190617_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('EWS', 'EWS'), ('General', 'General')], default='General', max_length=10),
        ),
    ]
