# Generated by Django 2.2 on 2019-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0014_auto_20190617_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.CharField(max_length=10, null=True, verbose_name='Date of Birth'),
        ),
    ]
