# Generated by Django 2.2 on 2019-06-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0015_auto_20190618_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('submitted_at',)},
        ),
    ]
