# Generated by Django 2.2 on 2019-06-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0016_auto_20190620_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-submitted_at',)},
        ),
    ]
