# Generated by Django 2.2 on 2019-06-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('phdfellows', '0017_auto_20190620_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhdFellows',
        ),
    ]
