# Generated by Django 2.2 on 2019-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0018_delete_phdfellows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='previous_status',
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='India', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
