# Generated by Django 2.2 on 2019-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0019_auto_20190624_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
