# Generated by Django 2.2 on 2019-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdfellows', '0020_auto_20190624_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='no_of_patents_granted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='no_of_peer_reviewed_publications',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
