# Generated by Django 2.2 on 2019-07-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AddField(
            model_name='announcements',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
