# Generated by Django 2.2 on 2019-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_auto_20190710_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_images', models.ImageField(upload_to='omr_sheets/%Y/%m/%d/%H:%M/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
